version: '3.8'

services:
  beancount-web:
    # 使用发布到DockerHub的镜像
    image: ${DOCKERHUB_USERNAME}/beancount-web:latest
    ports:
      - "8000:8000"
    volumes:
      # 挂载数据目录到宿主机，持久化数据
      - ./data:/app/data
      # 可选：挂载配置文件
      # - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - DATA_DIR=/app/data
      # 生产环境配置
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 生产环境安全设置
    user: "1000:1000"  # 非root用户运行
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true

  # Nginx反向代理（可选，生产环境推荐）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - beancount-web
    restart: unless-stopped 