"""Add details to sync_logs table

Revision ID: 37f86623daea
Revises: 3a467b23284a
Create Date: 2025-08-21 13:33:04.438412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f86623daea'
down_revision: Union[str, None] = '3a467b23284a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_logs', sa.Column('operation_type', sa.String(), nullable=True))
    op.add_column('sync_logs', sa.Column('files_count', sa.Integer(), nullable=True))
    op.add_column('sync_logs', sa.Column('duration', sa.Float(), nullable=True))
    op.create_index(op.f('ix_sync_logs_start_time'), 'sync_logs', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_start_time'), table_name='sync_logs')
    op.drop_column('sync_logs', 'duration')
    op.drop_column('sync_logs', 'files_count')
    op.drop_column('sync_logs', 'operation_type')
    # ### end Alembic commands ###
