"""Update recurring model with full fields

Revision ID: 3a467b23284a
Revises: 0c5f57533223
Create Date: 2025-08-21 13:25:09.494625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a467b23284a'
down_revision: Union[str, None] = '0c5f57533223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('name', sa.String(), nullable=False))
    op.add_column('recurring_transactions', sa.Column('recurrence_type', sa.String(), nullable=False))
    op.add_column('recurring_transactions', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('recurring_transactions', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('weekly_days', sa.JSON(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('monthly_days', sa.JSON(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('flag', sa.String(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('narration', sa.String(), nullable=False))
    op.add_column('recurring_transactions', sa.Column('links', sa.JSON(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('postings', sa.JSON(), nullable=False))
    op.add_column('recurring_transactions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('last_executed', sa.Date(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('next_execution', sa.Date(), nullable=True))
    op.drop_index('ix_recurring_transactions_period', table_name='recurring_transactions')
    op.drop_column('recurring_transactions', 'next_date')
    op.drop_column('recurring_transactions', 'description')
    op.drop_column('recurring_transactions', 'account')
    op.drop_column('recurring_transactions', 'amount')
    op.drop_column('recurring_transactions', 'period')
    op.drop_column('recurring_transactions', 'day')
    op.drop_column('recurring_transactions', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('currency', sa.VARCHAR(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('day', sa.VARCHAR(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('period', sa.VARCHAR(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('amount', sa.FLOAT(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('account', sa.VARCHAR(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('next_date', sa.DATE(), nullable=True))
    op.create_index('ix_recurring_transactions_period', 'recurring_transactions', ['period'], unique=False)
    op.drop_column('recurring_transactions', 'next_execution')
    op.drop_column('recurring_transactions', 'last_executed')
    op.drop_column('recurring_transactions', 'updated_at')
    op.drop_column('recurring_transactions', 'created_at')
    op.drop_column('recurring_transactions', 'is_active')
    op.drop_column('recurring_transactions', 'postings')
    op.drop_column('recurring_transactions', 'links')
    op.drop_column('recurring_transactions', 'narration')
    op.drop_column('recurring_transactions', 'flag')
    op.drop_column('recurring_transactions', 'monthly_days')
    op.drop_column('recurring_transactions', 'weekly_days')
    op.drop_column('recurring_transactions', 'end_date')
    op.drop_column('recurring_transactions', 'start_date')
    op.drop_column('recurring_transactions', 'recurrence_type')
    op.drop_column('recurring_transactions', 'name')
    # ### end Alembic commands ###
